### ISSUE TITLE
Cannot select/copy Text in Code Snippets

### ISSUE THREAD

**Issue by garygrossgarten** [notiz-dev/notiz#104]

**Comment by marcjulian** [comment]
![Screen Recording 2020-07-20 at 15 59 26](https://user-images.githubusercontent.com/8985933/87947157-37a10180-caa3-11ea-861c-dfc5be87a12c.gif)
@garygrossgarten is this what you mean? My selection is always removed automatically

**Comment by garygrossgarten** [comment]
yes

**Comment by marcjulian** [comment]
Strange behavior, might come from prismjs highlighting.

**Comment by marcjulian** [comment]
I tested it on prismjs docs and it is not happening there.

**Comment by marcjulian** [comment]
`ngAfterViewChecked` is triggered on text selection and highlight is always triggered again.

```ts
ngAfterViewChecked() {
    this.highlightService.highlightAll();
}
```

**Comment by marcjulian** [comment]
@garygrossgarten alternative could be [scully-plugin-prism-highlight](https://github.com/notiz-dev/notiz/pull/108)
