### ISSUE TITLE
analytics

### ISSUE THREAD

**Issue by garygrossgarten** [notiz-dev/notiz#15]

**Comment by marcjulian** [comment]
Do you mind trying out https://simpleanalytics.com/ ? Or do you have another preference?

**Comment by marcjulian** [comment]
<img width="973" alt="Screenshot 2020-02-27 at 10 58 41" src="https://user-images.githubusercontent.com/8985933/75433384-274f8500-5950-11ea-9d98-1a331b06eb58.png">

This is how it could look like with simple analytics. We could even integrated into the website if we wanted to https://docs.simpleanalytics.com/embed-graph-on-your-site

**Comment by garygrossgarten** [comment]
@marcjulian I'd rather use google analytics

**Comment by marcjulian** [comment]
@garygrossgarten okay, do you mind adding it?
