### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by garygrossgarten** [notiz-dev/notiz#5]

**Comment by marcjulian** [comment]
![logo](https://user-images.githubusercontent.com/8985933/75377828-e36a6a80-58d2-11ea-9344-4231e0d9a6d5.png)
![logo2](https://user-images.githubusercontent.com/8985933/75377834-e49b9780-58d2-11ea-8f2c-f99997569bb7.png)

**Comment by marcjulian** [comment]
@garygrossgarten wie findest du den Gradient?

**Comment by garygrossgarten** [comment]
Kannst du einen PR erstellen? Dann gucke ich es mir an.

**Comment by garygrossgarten** [comment]
Kannst du auch eine Variante mit dem notiz label in gradient daneben machen? Font wie im Projekt.

**Comment by marcjulian** [comment]
<img width="396" alt="Screenshot 2020-02-26 at 20 08 13" src="https://user-images.githubusercontent.com/8985933/75378334-c4b8a380-58d3-11ea-905e-49abd324baf3.png">

**Comment by marcjulian** [comment]
Die Font https://fonts.googleapis.com/css?family=Muli&display=swap ?

**Comment by marcjulian** [comment]
![logo-text](https://user-images.githubusercontent.com/8985933/75379331-7efcda80-58d5-11ea-9282-940c25b4cf26.png)

**Comment by marcjulian** [comment]
Ich kann den Gradient auch mehr wie der Button machen 

<img width="396" alt="Screenshot 2020-02-26 at 20 26 56" src="https://user-images.githubusercontent.com/8985933/75379851-5a553280-58d6-11ea-8e92-9a711345e282.png">

**Comment by marcjulian** [comment]
![Logo](https://user-images.githubusercontent.com/8985933/75380150-cfc10300-58d6-11ea-84db-c2ced8bf12eb.png)
