### ISSUE TITLE
Latest Article flicker on mouse hover

### ISSUE THREAD

**Issue by marcjulian** [notiz-dev/notiz#57]
Hover the mouse on the bottom edge and the cards are starting to flicker.

![Screen Recording 2020-04-16 at 20 35 09](https://user-images.githubusercontent.com/8985933/79494206-e7894d80-8022-11ea-91ed-3d8075028126.gif)

**Comment by garygrossgarten** [comment]
cant do anything about that without adding javascript/ typescript (currently css animation)
