### ISSUE TITLE
Newsletter Toast Position

### ISSUE THREAD

**Issue by garygrossgarten** [notiz-dev/notiz#61]

**Comment by marcjulian** [comment]
@garygrossgarten how to properly change the position? I guess toast needs `ion-content`, it is set to fixed to margin-bottom doesn't apply

**Comment by garygrossgarten** [comment]
As far as I'm concerned, this is due too tailwind purging to much. Should ne fixed with feature/tabs

**Comment by marcjulian** [comment]
What position do you expect? It is visible on page

**Comment by marcjulian** [comment]
![localhost_1668_ (1)](https://user-images.githubusercontent.com/8985933/81508697-eab3e880-9305-11ea-9982-5795dac8eb24.png)
